server:
  port: 8080
javax:
  sql:
    DataSource:
      test:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dataSource:
          url: jdbc:h2:mem:test
          user: sa
          password: ""